### ISSUE TITLE
conditional quasi Poisson regression

### ISSUE THREAD

**Issue by chongliang-luo** [hturner/gnm#13]
Hi, 
I'm wondering how do you estimate the dispersion parameter when doing conditional Poisson regression? I called gnm() and eliminate the strata (i.e. group, class) and set family = quasipoisson. My guess is this function first do conditional Poisson (which is a multinomial regression) and get the estimates of covariates' effects, then estimate the dispersion parameter (assumed common, for all stratae?) using the moment estimator. Can you clarify the algorithm, or provide any references? Thank you!

**Comment by hturner** [comment]
Hello,

In this respect, `gnm()` works the same way as `glm()`, regardless of whether you are using the `eliminate` argument or not. The score equations for GLMs do not depend on the dispersion parameter (see e.g. [my GLM course notes](http://statmath.wu.ac.at/courses/heather_turner/glmCourse_001.pdf), pp23-24). If the dispersion parameter is unknown, it is estimated by the moment estimator (GLM course, p29). 

For `family = poisson` the dispersion parameter is fixed to 1. For `family = quasipoisson` the dispersion parameter is treated as unknown and estimated. So with the same link function, the estimated coefficients will be exactly the same, but the standard errors from the quasi-Poisson model account for any over-dispersion. (There's an example on pp115-125 of the GLM course, using the `ships` data from **MASS**).

There is no special treatment for stratified models, a common dispersion parameter is assumed.

I haven't cited specific references in my course notes, but the Ship's Damage example is from the "Generalized Linear Models" book by McCullagh, P. and J.A. Nelder, so I probably drew from that. Other references I used that might be useful are listed here: http://statmath.wu.ac.at/courses/heather_turner/

**Comment by chongliang-luo** [comment]
Thank you Dr Turner!

**Comment by hturner** [comment]
Glad it helped.
